# Configuration file for backup.sh 
SCRIPTS="/home/rob/Files/Scripts"

# Configuration
DATE=$(date +%Y-%m-%d_%H.%M)
BACKUP="/mnt/backup/backup/"
BACKUP_LOG="$SCRIPTS/backup-errors-$DATE.log" 
BACKUP_VERSION="v3.0 January 4 2026"
EDITOR_CMD="kate"
NOTIFICATION_DURATION=4000
OLD_BACKUP_DIR="/mnt/backup/oldbackups/"
RETENTION_CYCLE=10
RUN_FILE="$SCRIPTS/backup.run"
SOURCE="/"
